[FEATURE] add support for changing the front-end voltage
delmic/jolt-control pull request #3
Opened 2023-07-13 14:25 UTC by pieleric

https://delmic.atlassian.net/browse/EB-122

In some (rare) cases, it's useful.
=> Allow to set it at init, via the config file.

2023-07-19 08:24 UTC, tepals requested changes

2023-07-19 08:24 UTC, tepals commented on src/jolt/driver/joltcb.py
> +            raise ValueError(f"Fontend offset voltage should be between 0 and 4065, got {val}")
```suggestion
            raise ValueError(f"Frontend offset voltage should be between 0 and 4095, got {val}")
```

2023-07-19 08:24 UTC, tepals commented on src/jolt/driver/joltcb.py
>          self.vacuum_pressure = int(3e3)  # �Bar
```suggestion
        self.vacuum_pressure = int(3e3)  # Bar
```

2023-07-19 08:24 UTC, tepals commented on src/jolt/gui/jolt_app.py
> +        # ambient == True means that the device should only be cooling down only
```suggestion
        # ambient == True means that the device should only be cooling down
```

2023-07-19 08:24 UTC, tepals commented on src/jolt/driver/joltcb.py
> +        # The command return a uint32
```suggestion
        # The command returns a uint32
```

2023-07-19 09:06 UTC, tepals approved these changes

2023-07-20 09:46 UTC, FCanberk approved these changes

2023-07-20 10:03 UTC, merged